//! Radicle Simulation Testing Framework
//!
//! This crate provides a high-level, ergonomic framework for writing integration
//! and simulation tests for Radicle networks. It abstracts away the complexities
//! of Kubernetes pod execution, identity management, and Radicle CLI interactions.

pub mod constants;
pub mod network;
pub mod node;

/// Sets up the network module and `require_network` helper for a given CUE instance.
///
/// This macro dynamically includes the auto-generated Rust bindings for the specified
/// CUE network topology file (generated by `build.rs`). It also generates a `require_network`
/// function that tests can call to ensure the network is provisioned and ready before executing.
///
/// To inspect these Rust definitions, they can be found in:
/// `./target/debug/build/radicle-simulation-*/out/*_bindings.rs`.
#[macro_export]
macro_rules! setup_network {
    ($name:expr) => {
        pub mod network {
            // Include the auto-generated bindings
            include!(concat!(env!("OUT_DIR"), "/", $name, "_bindings.rs"));
        }

        /// Ensures the simulated network is provisioned and ready for testing.
        ///
        /// This function initializes the test logger and applies the CUE network topology.
        /// It returns a reference-counted `NetworkGuard`. The network will remain active
        /// as long as at least one test holds a guard, and will be automatically torn down
        /// when the final guard is dropped (unless `PRESERVE_NETWORK=1` is set).
        pub fn require_network() -> std::sync::Arc<$crate::network::NetworkGuard> {
            // TODO(Ade): Doesn't feel right here, but is ergonomic
            let _ = env_logger::builder().is_test(true).try_init();
            $crate::network::apply_network(concat!("../instances/", $name, ".cue"))
        }
    };
}
