#[path = "commands/auth.rs"]
pub mod rad_auth;
#[path = "commands/checkout.rs"]
pub mod rad_checkout;
#[path = "commands/clone.rs"]
pub mod rad_clone;
#[path = "commands/edit.rs"]
pub mod rad_edit;
#[path = "commands/help.rs"]
pub mod rad_help;
#[path = "commands/init.rs"]
pub mod rad_init;
#[path = "commands/inspect.rs"]
pub mod rad_inspect;
#[path = "commands/issue.rs"]
pub mod rad_issue;
#[path = "commands/ls.rs"]
pub mod rad_ls;
#[path = "commands/merge.rs"]
pub mod rad_merge;
#[path = "commands/patch.rs"]
pub mod rad_patch;
#[path = "commands/push.rs"]
pub mod rad_push;
#[path = "commands/review.rs"]
pub mod rad_review;
#[path = "commands/rm.rs"]
pub mod rad_rm;
#[path = "commands/self.rs"]
pub mod rad_self;
#[path = "commands/track.rs"]
pub mod rad_track;
#[path = "commands/untrack.rs"]
pub mod rad_untrack;
