#[path = "commands/assign.rs"]
pub mod rad_assign;
#[path = "commands/auth.rs"]
pub mod rad_auth;
#[path = "commands/checkout.rs"]
pub mod rad_checkout;
#[path = "commands/clone.rs"]
pub mod rad_clone;
#[path = "commands/cob.rs"]
pub mod rad_cob;
#[path = "commands/delegate.rs"]
pub mod rad_delegate;
#[path = "commands/edit.rs"]
pub mod rad_edit;
#[path = "commands/fork.rs"]
pub mod rad_fork;
#[path = "commands/help.rs"]
pub mod rad_help;
#[path = "commands/id.rs"]
pub mod rad_id;
#[path = "commands/init.rs"]
pub mod rad_init;
#[path = "commands/inspect.rs"]
pub mod rad_inspect;
#[path = "commands/issue.rs"]
pub mod rad_issue;
#[path = "commands/label.rs"]
pub mod rad_label;
#[path = "commands/ls.rs"]
pub mod rad_ls;
#[path = "commands/node.rs"]
pub mod rad_node;
#[path = "commands/patch.rs"]
pub mod rad_patch;
#[path = "commands/path.rs"]
pub mod rad_path;
#[path = "commands/publish.rs"]
pub mod rad_publish;
#[path = "commands/remote.rs"]
pub mod rad_remote;
#[path = "commands/review.rs"]
pub mod rad_review;
#[path = "commands/rm.rs"]
pub mod rad_rm;
#[path = "commands/self.rs"]
pub mod rad_self;
#[path = "commands/sync.rs"]
pub mod rad_sync;
#[path = "commands/track.rs"]
pub mod rad_track;
#[path = "commands/unassign.rs"]
pub mod rad_unassign;
#[path = "commands/unlabel.rs"]
pub mod rad_unlabel;
#[path = "commands/untrack.rs"]
pub mod rad_untrack;
#[path = "commands/web.rs"]
pub mod rad_web;
