[package]
name = "radicle-keri"
homepage = "https://radicle.xyz"
repository = "https://app.radicle.xyz/seeds/seed.radicle.xyz/rad:z3gqcJUoA1n9HaHKufZs5FCSGazv5"
license = "MIT OR Apache-2.0"
edition = "2021"
version = "0.9.0"

[dependencies]
keri-controller = "0.12.7"
keri-core = "0.12.7"