[package]
name = "radicle-cob"
version = "0.21.1"
description = "Radicle Collaborative Objects library"

keywords = ["radicle", "cob", "cobs"]

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = []
# Only used for testing. Ensures that commit ids are stable.
stable-commit-ids = []
test = []

[dependencies]
fastrand = { workspace = true }
radicle-git-ref-format = { workspace = true }
git2 = { workspace = true, optional = true }
log = { workspace = true }
nonempty = { workspace = true, features = ["serialize"] }
radicle-crypto = { workspace = true, features = ["ssh"] }
radicle-dag = { workspace = true }
radicle-git-metadata = { workspace = true }
radicle-oid = { workspace = true, features = ["git2", "serde", "sha1", "std"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true, default-features = true }

[dev-dependencies]
fastrand = { workspace = true }
qcheck = { workspace = true }
qcheck-macros = { workspace = true }
radicle-crypto = { workspace = true, features = ["test", "radicle-git-ref-format"] }
radicle-git-ref-format = { workspace = true, features = ["macro"] }
radicle-oid = { workspace = true, features = ["qcheck"] }
tempfile = { workspace = true }
