// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

@if(!debug)

package main

// Defaults
values: {
	// The topology map allows defining multiple node groups with different versions
	topology: [string]: {
		//
		// Open enum for allowed image versions (allows custom local builds via `string`)
		// This is kept here so the update-image-tags.sh script can easily modify it.
		//
		version: "1.2.0" | "1.4.0" | "1.5.0" | "1.5.0-" | "1.5.0-amd64" | "1.5.0-arm64" | "1.6.0" | "1.6.1" | "1.7.0" | "1.7.1" | "1.8.0" | "latest" | "main" | "production" | "sqlite-patch" | string | *"latest"
		...
	}

	// Provide a default node so that a basic install works out-of-the-box
	topology: "default-node": {
		role: "seed"
		replicas: 1
	}
}
