[package]
name = "radicle-systemd"
description = "Radicle integration with Systemd"
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
version = "0.9.0"
rust-version.workspace = true
