[package]
name = "radicle-systemd"
version = "0.13.0"
description = "Radicle integration with Systemd"

edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
log = { workspace = true, optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
systemd-journal-logger = { version = "2.2.2", optional = true }

[features]
default = ["journal", "listen"]
journal = ["dep:log", "dep:systemd-journal-logger"]
listen = []