#!/bin/sh
set -e

tag=$(git describe)
version=$(echo $tag | sed 's/^v//')

echo "# 👾 Radicle $version"
echo
echo "Radicle $version ($(git rev-parse --short HEAD)) is released."
echo
echo "## Installation"
echo
echo '```'
echo "curl -sSf https://radicle.xyz/install | sh -s -- --no-modify-path --version=$version"
echo '```'
echo
echo "## Notes"
echo
echo "* This update is recommended for everyone. No manual intervention is required."
echo
echo "## Changelog"
echo

git log --pretty=format:'* `%h` **%s** *<%ae>*' $(git describe --abbrev=0 HEAD^)..HEAD

echo
echo "## Checksums"
echo

echo '```'
build/checksums
echo '```'
