[package]
name = "radicle-signals"
version = "0.12.0"
description = "Radicle signal handling"

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }
signals_receipts = { version = "0.2.0", features = ["channel_notify_facility"] }

[target.'cfg(windows)'.dependencies.windows]
workspace = true
features = [
    "Win32_Foundation",
    "Win32_System_Console",
]
