[package]
name = "radicle-git-ref-format"
version = "0.1.0"
description = "Radicle re-exports and macros for `git-ref-format-core`"

categories = ["no-std"]
keywords = ["radicle", "git", "refname", "ref", "references"]

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
macro = []
bstr = ["git-ref-format-core/bstr"]
serde = ["git-ref-format-core/serde"]

[dependencies]
git-ref-format-core.workspace = true
