[package]
name = "radicle-oid"
version = "0.2.1"
description = "Radicle representation of Git object identifiers"

keywords = ["radicle", "git", "oid"]

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

# For documentation of features refer to the module documentation in `./lib.rs`
[features]
default = ["sha1", "std"]
gix = ["dep:gix-hash"]
std = []
sha1 = []

[dependencies]
git2 = { workspace = true, optional = true, default-features = false }
gix-hash = { workspace = true, optional = true }
qcheck = { workspace = true, optional = true, default-features = false }
radicle-git-ref-format = { workspace = true, optional = true, default-features = false }
schemars = { workspace = true, optional = true, default-features = false }
serde = { workspace = true, optional = true, default-features = false }

[dev-dependencies]
git2 = { workspace = true }
gix-hash = { workspace = true }
qcheck = { workspace = true }
qcheck-macros = { workspace = true }
