name: Deploy

on:
  push:
    branches:
      - deploy/*

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to the container registry
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build and push radicle-node
        id: radicle-node
        uses: docker/build-push-action@v4
        with:
          context: .
          file: radicle-node/Dockerfile
          push: true
          tags: gcr.io/radicle-services/radicle-node:latest,gcr.io/radicle-services/radicle-node:${{ github.sha }}
          cache-from: type=registry,ref=gcr.io/radicle-services/radicle-node:latest
          cache-to: type=inline
      - name: Build and push radicle-httpd
        id: radicle-httpd
        uses: docker/build-push-action@v4
        with:
          context: .
          file: radicle-httpd/Dockerfile
          push: true
          tags: gcr.io/radicle-services/radicle-httpd:latest,gcr.io/radicle-services/radicle-httpd:${{ github.sha }}
          cache-from: type=registry,ref=gcr.io/radicle-services/radicle-httpd:latest
          cache-to: type=inline

  deploy-to-seed:
    runs-on: ubuntu-latest
    needs: build-and-push-images
    strategy:
      matrix:
        hostname: [seed]
        include:
        - user: github-actions
        - host: seed.radicle.xyz
    steps:
      - shell: bash
        run: |
          echo "$GEOAVAIL_SEED_SSH_PRIVATE_KEY" >ssh-private-key
          chmod go-rwx ssh-private-key
          ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ssh-private-key ${{ matrix.user }}@${{ matrix.host }} "curl https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/.env.${{ matrix.hostname }} >.env"
          ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ssh-private-key ${{ matrix.user }}@${{ matrix.host }} "curl https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/docker-compose.yml >docker-compose.yml"
          ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ssh-private-key ${{ matrix.user }}@${{ matrix.host }} "docker system prune --all --force"
          ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ssh-private-key ${{ matrix.user }}@${{ matrix.host }} "RADICLE_IMAGE_TAG=${{ github.sha }} docker-compose --file docker-compose.yml pull"
          ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ssh-private-key ${{ matrix.user }}@${{ matrix.host }} "RADICLE_IMAGE_TAG=${{ github.sha }} docker-compose --file docker-compose.yml down"
          ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ssh-private-key ${{ matrix.user }}@${{ matrix.host }} "RADICLE_IMAGE_TAG=${{ github.sha }} docker-compose --file docker-compose.yml up --detach"
        env:
          GEOAVAIL_SEED_SSH_PRIVATE_KEY: ${{ secrets.GEOAVAIL_SEED_SSH_PRIVATE_KEY }}
